fly_app/routes.py
from flask import (
    render_template,
    request,
    url_for,
    session,
    redirect,
    json,
    flash,
    Blueprint,
    current_app,
)
from fly_app.forms import FlightSearchForm, LiveFlightSearchForm
from .amadeus import Amadeus, date_span, date_time_formatter
from datetime import date, datetime  # , timedelta
import os.path
from isodate import parse_duration

bp = Blueprint("routes", __name__, static_folder="./static")

search = Amadeus()
code_dir = os.path.join(bp.static_folder, "JSON/optd_codes.json")
with open(code_dir) as f:
    code_dict = json.load(f)
currency_dir = os.path.join(bp.static_folder, "JSON/xe_currency_list.json")
with open(currency_dir) as f:
    currencies = json.load(f)


def full_string(param_type, key):
    if key in [
        "origin",
        "originLocationCode",
        "destination",
        "destinationLocationCode",
    ]:
        code = "C" + session[param_type][key]
        string = code_dict[code]["string"]
        fullString = code[1:] + " " + string
    else:
        code = session[param_type][key]
        string = currencies[code]
        fullString = code + " " + string
    return fullString


@bp.route("/")
@bp.route("/index")
def index():
    return render_template("index.html")


@bp.route("/flight_search/wide_open", methods=["GET", "POST"])
def flight_search():
    if request.args.get("new") != "false":
        session["params"] = {  # Needed to avoid keyError
            "oneWay": False,
            "nonStop": False,
            "viewBy": "DESTINATION",
        }
        session["strings"] = {"origin": "", "destination": ""}
    values = session["params"]
    strings = session["strings"]
    one_way = session["params"]["oneWay"]
    direct = session["params"]["nonStop"]
    search_type = request.args.get("search_type", "inspiration")
    if search_type == "extensive":
        form = FlightSearchForm(aggregation=values["viewBy"])
    else:
        form = FlightSearchForm(aggregation="DESTINATION")
    if form.validate_on_submit():
        session["params"] = {}
        session["strings"] = {}
        session["params"]["origin"] = form.origin.data.split()[0].upper()
        session["strings"]["origin"] = form.origin.data
        session["params"]["oneWay"] = form.one_way.data
        if form.destination.data:
            search_type = "extensive"
            destination_ = form.destination.data
            session["strings"]["destination"] = destination_
            session["params"]["destination"] = destination_.split()[0].upper()
            session["params"]["viewBy"] = form.aggregation.data
        else:
            search_type = "inspiration"
            session["params"]["viewBy"] = "DESTINATION"
        if not form.one_way.data:
            if form.min_duration.data and form.max_duration.data:
                session["params"]["duration"] = (
                    str(form.min_duration.data) + "," + str(form.max_duration.data)
                )
            elif form.min_duration.data:  # and not form.max_duration.data:
                session["params"]["duration"] = str(form.min_duration.data)
            elif form.max_duration.data:  # and not form.min_duration.data:
                session["params"]["duration"] = str(form.max_duration.data)
        if form.departure_date1.data and form.departure_date2.data:
            departure_date1 = date.strftime(form.departure_date1.data, "%Y-%m-%d")
            departure_date2 = date.strftime(form.departure_date2.data, "%Y-%m-%d")
            session["params"]["departureDate"] = departure_date1 + "," + departure_date2
        elif form.departure_date1.data:  # and not form.departure_date2.data:
            session["params"]["departureDate"] = date.strftime(
                form.departure_date1.data, "%Y-%m-%d"
            )
        elif form.departure_date2.data:  # and not form.departure_date1.data:
            session["params"]["departureDate"] = date.strftime(
                form.departure_date2.data, "%Y-%m-%d"
            )
        session["params"]["nonStop"] = form.direct_only.data
        if form.max_price.data:
            session["params"]["maxPrice"] = form.max_price.data
        return redirect(url_for("routes.results", search_type=search_type))
    else:
        if form.errors:  # To avoid problem with disableEnable() of duration
            form.one_way.data = False  # Unchecks 'One-way' field
            error_count = len(form.errors.keys())
        else:
            error_count = 0
        return render_template(
            "search.html",
            form=form,
            code_dict=code_dict,
            search_type=search_type,
            one_way=one_way,
            direct=direct,
            values=values,
            strings=strings,
            error_count=error_count,
        )


@bp.route("/results/wide_open", methods=["GET", "POST"])
def results():
    if not request.referrer and not current_app.testing:
        flash(
            """It looks as if you tried accessing results directly through
            the address bar. Results can only be accessed through this search
            page."""
        )
        return redirect(url_for("routes.flight_search"))
    search_type = request.args.get("search_type")
    if request.args.get("referrer"):
        search_type = "extensive"
        # nonStop and oneWay end up as a strings
        session["params"]["nonStop"] = bool(
            session["params"]["nonStop"] == "true"
        )  # string to boolean
        session["params"]["oneWay"] = bool(
            session["params"]["oneWay"] == "true"
        )  # string to boolean
        # Render full strings when Modify Search selected
        session["strings"] = {}
        session["strings"]["origin"] = full_string("params", "origin")
        session["strings"]["destination"] = full_string("params", "destination")
    params = session["params"]
    # currencies = search.CURRENCIES
    flights = search.flight_search(search_type, **params)
    try:
        results = flights["data"]
        return render_template(
            "results.html",
            title="WideOpen Search Results",
            search_type=search_type,
            flights=flights,
            results=results,
            code_dict=code_dict,
            date_span=date_span,
            currencies=currencies,
            set=set,
            list=list,
        )
    except KeyError:
        current_app.logger.exception("Search Parmeters: " + str(params) + str(flights))
        flash(
            """Sorry, we did not find any matching flights.
            Try modifying your search."""
        )
        return redirect(
            url_for("routes.flight_search", new="false", search_type=search_type)
        )


# New flight-offers API requires booleans as strings, eg, 'false', not False
@bp.route("/live_flight_search", methods=["GET", "POST"])
def live_search():
    def immunize(form_data, integer=0):
        if form_data is None:
            form_data = integer
        return form_data

    if request.args.get("new") != "false":
        session["live_params"] = {  # Needed to avoid keyError
            "currencyCode": "USD",
            "nonStop": "false",
            "adults": 1,
            "children": 0,
            "infants": 0,
            "travelClass": "ECONOMY",
        }
        session["live_strings"] = {
            "origin": "",
            "destination": "",
            "currency": "USD US dollars",
        }
    values = session["live_params"]
    strings = session["live_strings"]
    direct = session["live_params"]["nonStop"]
    form = LiveFlightSearchForm(travelClass=values["travelClass"])
    airlines_dir = os.path.join(current_app.static_folder, "JSON/optd_airlines.json")
    with open(airlines_dir) as f:
        airlines_dict = json.load(f)
    if form.validate_on_submit():
        session["live_params"] = {}
        session["live_strings"] = {}
        origin_code = form.origin.data.split()[0].upper()
        session["live_params"]["originLocationCode"] = origin_code
        session["live_strings"]["origin"] = form.origin.data
        destination_code = form.destination.data.split()[0].upper()
        session["live_params"]["destinationLocationCode"] = destination_code
        session["live_strings"]["destination"] = form.destination.data
        currency_code = form.currency.data.split()[0].upper()
        session["live_params"]["currencyCode"] = currency_code
        session["live_strings"]["currency"] = form.currency.data
        session["live_params"]["nonStop"] = str(form.nonStop.data).lower()
        session["live_params"]["departureDate"] = date.strftime(
            form.departureDate.data, "%Y-%m-%d"
        )
        if form.returnDate.data:
            session["live_params"]["returnDate"] = date.strftime(
                form.returnDate.data, "%Y-%m-%d"
            )
        session["live_params"]["adults"] = immunize(form.adults.data, integer=1)
        session["live_params"]["children"] = immunize(form.children.data)
        session["live_params"]["infants"] = immunize(form.infants.data)
        session["live_params"]["travelClass"] = form.travelClass.data

        # New flight-offers API does have arrivalBy/returnBy GET parmaters
        # if form.arrivalBy.data:
        #     arrive_dt = datetime.combine(
        #         form.departureDate.data, form.arrivalBy.data.time())
        #     if form.departurePlusOne.data:
        #         arrive_dt = arrive_dt + timedelta(days=1)
        #     session['live_params']['arrivalBy'] = datetime.strftime(
        #         arrive_dt, '%Y-%m-%dT%H:%M')
        # if form.returnBy.data:
        #     return_dt = datetime.combine(
        #         form.returnDate.data, form.returnBy.data.time())
        #     if form.returnPlusOne.data:
        #         return_dt = return_dt + timedelta(days=1)
        #     session['live_params']['returnBy'] = datetime.strftime(
        #         return_dt, '%Y-%m-%dT%H:%M')

        if form.includeAirlines.data:

fly_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% if title %}
    <title>{{ title }}</title>
  {# {% else %}
    <title>WideOpen Flight Search: Ultra-Flexible Dates & Destinations</title> #}
  {% endif %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="keywords" content="travel, flights, airfare, flexible">
  {# <meta name="author" content="Steven Zekowski">  #}
  <meta name="google-site-verification" content="Q84ISZKvSy9xH6JJP5Zu13kB6x3KGldwtWLufaNWxYI" />
  <link rel="stylesheet" href="{{ url_for('static', filename='CSS/w3.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='CSS/custom.css') }}">
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.min.css" integrity="sha384-kcAOn9fN4XSd+TGsNu2OQKSuV5ngOwt7tg73O4EpaD91QXvrfgvf0MR7/2dUjoI6" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link href="https://fonts.googleapis.com/css?family=Lato&subset=latin-ext&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:500i,600,600i,700,700i&display=swap" rel="stylesheet">
  <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>

  {% block head %}{% endblock %}

  {% block style %}{% endblock %}
</head>

<body>
<div class="w3-top">
  <nav class="w3-bar w3-blue" id="myNavbar">
    <a href="/index" class="w3-bar-item w3-button">HOME</a>
    <div class="w3-dropdown-hover">
      <button class="w3-button">FLIGHT SEARCH</button>
      <div class="w3-dropdown-content w3-bar-block w3-card-4">
        <a href="{{ url_for('routes.flight_search') }}" class="w3-bar-item w3-button">WideOpen Search</a>
        <a href="{{ url_for('routes.live_search') }}" class="w3-bar-item w3-button">Live Search</a>
      </div>
    </div>
  </nav>
</div>
{% block content %}{% endblock %}
<footer class="w3-bottom">
  <small>
    Copyright &copy; 2019 - <span id="currentYear"></span>, Steven Zekowski. All Rights Reserved.
  </small>
  <span><a href="mailto:admin@wideopenflights.com">Contact Us</a></span>
</footer>

<script>
  var d = new Date();
  document.getElementById("currentYear").innerHTML = d.getFullYear();
</script>
{% block script %}{% endblock %}
</body>
</html>

fly_app/templates/index.html
{% extends "base.html" %}

{% block head %}
  <title>WideOpen | Flexible Flight Search to Anywhere & Everywhere</title>
  <meta name="description" content="Find inspiring destinations, the cheapest dates, and the best trip-length options — all with a single search.">
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<div class="bg-img img5 fluid-type">
  <div class="title w3-center">
    WideOpen Flights
  </div>
  <div class="subtitle w3-center">
    A New Way to Search
  </div>
  <div class="w3-row position-low index-container fluid-box">
    <div class="slides pad-sides animate-fading">
      <div class="slide-title">Another flight search website... Why?</div>
      <p>
        <span class="slide-subtitle">
          <a href="{{ url_for('routes.flight_search') }}">WideOpen Search</a>
        </span>
        lets you search all destinations, over any date range!&emsp;
        Only an origin city is required.
      </p>
      <pre>&#9;&#9;With a single search...</pre>
    </div>
    <div class="slides pad-sides animate-fading">
      <p>
        ...explore dates, price, and trip-length options for hundreds of destinations.
      </p>
      <p>
        Then use <span class="slide-subtitle">
        <a href="{{ url_for('routes.live_search') }}">&emsp;Live Search</a>
        </span>
        to check real-time availability, prices, flight duration, layovers, and aircraft type.
      </p>
    </div>
    <div class="slides pad-sides animate-fading">
      <p>Ready to try something new?</p>
      <p class="w3-center slide-title">
        <a href="{{ url_for('routes.flight_search') }}">WideOpen Search &rarr;</a>
      </p>
      {# <p class="w3-center slide-title">
        <a href="{{ url_for('routes.live_search') }}">Live Search &rarr;</a>
      </p> #}
    </div>
    <div class="previous w3-hover-text-green pad-sides" onclick="plusDivs(-1)">&#10094;</div>
    <div class="next w3-hover-text-green pad-sides" onclick="plusDivs(1)">&#10095;</div>
    <div class="w3-center">
      <span class="w3-badge dots w3-border w3-transparent w3-hover-green" onclick="currentDiv(1)"></span>
      <span class="w3-badge dots w3-border w3-transparent w3-hover-green" onclick="currentDiv(2)"></span>
      <span class="w3-badge dots w3-border w3-transparent w3-hover-green" onclick="currentDiv(3)"></span>
    </div>
  </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>
// Borrowed from https://www.w3schools.com/howto/howto_js_slideshow.asp & 
// https://stackoverflow.com/questions/40638969/automatic-and-manual-slideshow
var slideIndex = 1;
var timer = null;
showDivs(slideIndex);

function plusDivs(n) {
  clearTimeout(timer);
  showDivs(slideIndex += n);
}

function currentDiv(n) {
  clearTimeout(timer);
  showDivs(slideIndex = n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("slides");
  var dots = document.getElementsByClassName("dots");
  if (n==undefined) {n = ++slideIndex}
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" w3-blue", "");
  }
  x[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " w3-blue";
  if (slideIndex != 3) {
    timer = setTimeout(showDivs, 8000);
  }
  else {
    x[slideIndex -1].className = x[slideIndex-1].className.replace(" animate-fading", "");
  }
}
</script>
{% endblock %}

fly_app/templates/live_results.html
{% extends "base.html" %}

{% block style %}
{% endblock %}

{% block content %}
{# <br><br> #}

<div class="bg-img img6 fluid-type">
  <div class="live-results-title">Live Search Results
    <div class="w3-cell-row live-row default-bg-color">
      {% if result_type == 'inspiration' or result_type == 'extensive' %}
      <div class="w3-cell w3-mobile w3-center">
        <a href="{{ url_for('routes.results', search_type=result_type) }}">
        <strong>&#8592;&nbsp;Back to <em>WideOpen</em> Results
        </strong>
        </a>
      </div>
      {% endif %}
      <div class="w3-cell w3-mobile w3-center">
        <a href="{{ url_for('routes.live_search', new='false') }}">
        <strong>&#8592;&nbsp;Modify this <em>Live</em> Search
        </strong>
        </a>
      </div>
    </div>
    <div class="w3-cell-row live-row default-bg-color">
      <div class="w3-cell w3-mobile w3-center">Filter By: </div>
      <div class="w3-cell w3-mobile w3-center">
        <label for="filter_layover">Maximum layover</label>
        <input type="text" id="filter_layover" placeholder="hours" onkeyup="filter()">
      </div>
      <div class="w3-cell w3-mobile w3-center">
        <label for="filter_stops">&nbsp;&nbsp;&nbsp;Maximum stops</label>
        <input type="text" id="filter_stops" onkeyup="filter()">
      </div>
      {# For troubleshooting #}
        {# <p>{{ session.live_params }}</p> #}
        {# '{{ request.referrer }}' #}
        {# <p>{{ flights }}</p> #}
        {# {% if flights.errors is defined %} #}
          {# {{ flights.errors }} #}
        {# {% endif %} #}
    </div>
  </div>

  <div class="wrapper-tall">
    {% for result in results %} 
    <div class="w3-margin result-card default-bg-color">
      <div class="w3-row w3-light-blue result-card-price-bar">
        <div class="w3-container w3-col third">
          <p><strong>
            {# {{ result.offerItems[0].pricePerAdult.total }} {{ flights.meta.currency }} per adult #}
            {{ result.travelerPricings[0].price.total }} {{ result.price.currency }} per adult
          </strong></p>
        </div>
        <div class="w3-container w3-col third w3-center">
          <p><strong>{{ result.price.total }} {{ result.price.currency }} Total: {{ session.live_params.adults }} adult
          {% for passenger_count in [(session.live_params.children,
          'child'), (session.live_params.infants, 'infant')] %}
            {% if passenger_count[0] > 0 %}
            , {{ passenger_count[0] }} {{ passenger_count[1] }}
            {% endif %}
          {% endfor %}
          </strong></p>
        </div>
      </div>

      {# {% for service in result.offerItems[0].services %} #}
      {% for itinerary in result.itineraries %}
      
      {# {% if result.offerItems[0].services.index(service) == 0 %} #}
      {% if result.itineraries.index(itinerary) == 0 %}
        <div class="w3-row w3-container"><p><strong>Outbound</strong></p></div>
      
      {# {% elif len(result.offerItems[0].services) == 2 and result.offerItems[0].services.index(service) == 1 %} #}
      {% elif len(result.itineraries) == 2 and result.itineraries.index(itinerary) == 1 %}
        <div class="w3-row w3-container"><p><strong>Return</strong></p></div>
      {% endif %}

        {# {% for segment in service.segments %} #}
        {% for segment in itinerary.segments %}
        
        {# {% if result.offerItems[0].services.index(service) == 0 %} #}
        {% if result.itineraries.index(itinerary) == 0 %}
        <div class="w3-row w3-container out">
        
        {# {% elif len(result.offerItems[0].services)==2 and result.offerItems[0].services.index(service)==1 %} #}
        {% elif len(result.itineraries)==2 and result.itineraries.index(itinerary)==1 %}
        <div class="w3-row w3-container return">
        {% endif %}

          <div class="w3-container col-15">
            <p title="{{ code_dict['A' + segment.departure.iataCode]['name'] }} to {{ code_dict['A' + segment.arrival.iataCode]['name'] }}">
              {{ segment.departure.iataCode }} to {{ segment.arrival.iataCode }}
            {% if itinerary.segments.index(segment) < (len(itinerary.segments) - 1) and segment.arrival.iataCode != itinerary.segments[itinerary.segments.index(segment) + 1].departure.iataCode %}
              <p class="w3-text-red">
              <strong>Connects Through Different Airports!</strong></p>
            {% endif %}
            </p>
          </div>
          <div class="w3-container col-20">
            <p> {{ flights.dictionaries.carriers[segment.carrierCode]|default('Carrier missing')|title }}&nbsp;&nbsp;Flight {{ segment.number }}
            <br><span class="w3-text-gray">{{ flights.dictionaries.aircraft[segment.aircraft.code]|default('Aircraft info missing')|title }}
            </span></p>
          </div>
          <div class="w3-container col-20">
            <p>Departs {{ strftime(date_time_formatter(segment.departure.at), '%a %d %b %Y at %I:%M %p') }}
            {% if segment.operating is defined %}
            <br><span class="w3-text-gray">Operated by {{ flights.dictionaries.carriers[segment.operating.carrierCode]|default('Carrier missing')|title }}
            </span>
            {% endif %}
            </p>
          </div>
          <div class="w3-container col-15">
          {# {% with td = date_time_formatter(segment.arrival.at) - date_time_formatter(segment.departure.at) %} #}
          {% with td = parse_duration(segment.duration) %}
            <p class="w3-text-gray w3-center">{{ '{} hours {} minutes'.format(*str(td).split(':')[:2]) }}</p>
          {% endwith %}
          </div>
          <div class="w3-container col-20">
            <p>Arrives {{ strftime(date_time_formatter(segment.arrival.at), '%a %d %b %Y at %I:%M %p') }}
            {# {% if date_time_formatter(segment.arrival.at).day != date_time_formatter(segment.departure.at).day %}
            <br><span class="w3-text-red">
            <strong>Arrives {{ date_span(itinerary.segments[0].departure.at, segment.arrival.at) }} calendar days later!</strong>
            </span>
            {% endif %} #}
            {% if len(itinerary.segments) > 1 and itinerary.segments.index(segment) != len(itinerary.segments) - 1  %}
            {% with layover = date_time_formatter(itinerary.segments[itinerary.segments.index(segment)+1].departure.at) - date_time_formatter(segment.arrival.at) %}
            <br><span class="w3-text-blue layover">
            <strong>Layover {{ '{} hours {} minutes'.format(*str(layover).split(':')[:2]) }}</strong>
            </span>
            {% endwith %}
            {% endif %}
            {% if itinerary.segments.index(segment) == len(itinerary.segments) -1 %}
            {# {% with total = date_time_formatter(segment.arrival.at) - date_time_formatter(itinerary.segments[0].departure.at) %} #}
            {% with total = parse_duration(itinerary.duration) %}
            <br><span class="w3-text-blue">
            <strong>Total duration {{ '{} hours {} minutes'.format(*str(total).split(':')[:2]) }}</strong>
            </span>
            {% endwith %}
              {% if date_time_formatter(segment.arrival.at).day != date_time_formatter(itinerary.segments[0].departure.at).day %}
              <br><span class="w3-text-red">
              <strong>Arrives {{ date_span(itinerary.segments[0].departure.at, segment.arrival.at) }} calendar days later!</strong>
              </span>
              {% endif %}
            {% endif %}
            </p>
          </div>
          <div class="w3-container col-10">
            <p>
              {# {{ segment.pricingDetailPerAdult.travelClass }} #}
              {% with sid = segment.id, d = result.travelerPricings[0].fareDetailsBySegment %}
              {% with details = d | selectattr("segmentId", "==", sid) | list | first %}
              {{ details.cabin }}
              {% endwith %}
              {% endwith %}
            </p>
          </div>
        </div>
        {% endfor %}
      
      {% endfor %}

    </div>
    {% endfor %}
  </div>
</div>
{# <div class="w3-container" id="test"></div> #}
{% endblock %}

{% block script %}
<script>

// NEED TO COMBINE THESE INTO ONE FUNCTION
function filter() {
  var input1, input2, filter1, filter2, i;
  input1 = document.getElementById("filter_layover");
  input2 = document.getElementById("filter_stops");
  filter1 = parseInt(input1.value);
  filter2 = parseInt(input2.value);
  var cards = document.getElementsByClassName("result-card");
  for (i = 0; i < cards.length; i++) {
    var collection = cards[i].querySelectorAll("span.layover");
    var layovers = [];
    var j;
    for (j = 0; j < collection.length; j++) {
      var layover = collection[j].getElementsByTagName("strong")[0].innerHTML;
      layovers.push( Number(layover.split(" ")[1]) + Number(layover.split(" ")[3]) / 60 );
      }
    var max_layover = Math.max.apply(null, layovers);
    var outs = cards[i].querySelectorAll("div.out");
    var returns = cards[i].querySelectorAll("div.return");
    if (max_layover > filter1 || outs.length > (filter2 + 1) || returns.length > (filter2 + 1)) {
      cards[i].style.display = "none";
      } 
    else {
      cards[i].style.display = "";
      }
  }
}

</script>
{% endblock %}